# Generated by Django 5.1.1 on 2024-09-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_alter_image_id_alter_image_image_alter_image_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='annotations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
